### ISSUE TITLE
When will the code be made avaliable?

### ISSUE THREAD

**Issue by sazzy4o** [Shark-NLP/CoNT#2]
Really interesting paper! I was wondering, when will the code be made available for it?

**Comment by ChenxinAn-fdu** [comment]
The code will be available at September 15~

**Comment by BinhMinhs10** [comment]
> The code will be available at September 15~

Is the code made avaliable??

**Comment by ChenxinAn-fdu** [comment]
The code is available now ! Feel free to email me or open an issue if you have any difficulty in running the code
