### ISSUE TITLE
代码的问题

### ISSUE THREAD

**Issue by MrBlack0220** [Shark-NLP/CoNT#3]
您好，很有趣的工作！
我想请问一下，CoNT-main/model/model.py在CoNTGenerator类的forward函数中
distance_mask = (actual_distance < 0.48)    
这一行代码是什么意思？0.48是超参数吗？
感谢您的回复！

**Comment by ChenxinAn-fdu** [comment]
你好！感谢对我们工作的关注

这一行主要是找到 这个sample它自己的ground truth ，因为torch_ngram = (number of matched ngram) / (sys_len + ref_len) 
最大值的0.5 但是 如果大于0.48 基本上可以认为是完全一样的了。

有什么欢迎继续提问
