### ISSUE TITLE
数据读取部分的问题

### ISSUE THREAD

**Issue by Luoyang144** [Shark-NLP/CoNT#5]
您好，我正打算使用CoNT进行文本摘要相关的对比学习，数据格式是CSV，两列内均为str类型文本。经过对代码进行一定修改后，在process_data函数内遇到了一些问题，包括：

- target和source是否为content和label的列名，我对内容进行修改后可以通过运行
- instance显示应该为一个列表，我将文本修改为[文本]的格式，尽管这样可以通过数据处理部分的代码，但是会在训练部分报错，报错内容为`fastNLP.core.collators.padders.exceptions.EleDtypeUnsupportedError: Fail to get padder for field:target_outp. `TorchNumberPadder` only supports padding python numbers or numpy numbers or torch.Tensor but get `<class 'str'>`. To view more information please set logger's level to DEBUG.`

是否可以提供一下数据格式的说明，以便更好的应用代码？感谢您的贡献。

**Comment by ChenxinAn-fdu** [comment]
文本摘要任务的话 可以用pandas从csv中把数据集读出来存储为jsonl 的格式 然后再调用`preprocess.py` 进行预处理 最后读入dataloader中

**Comment by ChenxinAn-fdu** [comment]
我猜你应该是忘了 preprocessing 这部分要把str -> id

**Comment by Luoyang144** [comment]
Yoo~，好像是的，这样的话只需要修改dataloader中的数据路径就可以？谢谢您的回复
