### ISSUE TITLE
一个读取模型部分的小bug

### ISSUE THREAD

**Issue by Luoyang144** [Shark-NLP/CoNT#6]
https://github.com/Shark-NLP/CoNT/blob/959a262ef83af00049bd6adc67b296fdd85ae6e1/model/model.py#L17
这一行的条件语句有一点点问题，应该改成`elif self.PTM == "t5" or self.PTM == "codet5":`.

**Comment by ChenxinAn-fdu** [comment]
谢谢 已经修正
